#!/bin/bash
# Copyright (C) 2018 Ernest Shefer <shef-er@ya.ru>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

LED=$(xset q | grep LED | awk '{ print $10 }'| sed 's/[^0-9]//g')
QUERY=$(expr $(echo $LED | cut -c 5) + 1)
LAYOUT=$(setxkbmap  -query | grep layout | awk '{print $2}' | cut -d, -f$QUERY)

#------------------------------------------------------------------------

usage() {
cat <<EOF
Usage: keyboard [OPTION]

    -h    print this message
    -i    print icon path
EOF
}

icon() {
  echo ".config/openbox/icons/indicator-keyboard-$LAYOUT.png"
}

while getopts ":hi" opt; do
  case $opt in
    h)
      usage
      exit 1
      ;;
    i)
      icon
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument"
      exit 1
      ;;
  esac
done

echo "$LAYOUT" | awk '{print toupper($0)}'

