#!/bin/sh
# Copyright (C) 2017 Ernest Shefer <shef-er@ya.ru>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CURRENT=$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f2)

echo -n $(xprop -id $CURRENT _NET_WM_NAME | cut -d= -f2 | sed 's\"\\g')
